#ifndef TIVOSERVICEKIT_GLOBAL_H
#define TIVOSERVICEKIT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TIVOSERVICEKIT_LIBRARY)
#  define TIVOSERVICEKITSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TIVOSERVICEKITSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TIVOSERVICEKIT_GLOBAL_H
